### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by wdomanskihmrc**
Updated content for GAAD 2024

### CODE REVIEW

**Comment by wdomanskihmrc** [comment]
@shabana-ali or @lammyjjones could you review and approve please

**Review by lammyjjones — APPROVED** [review]

**Review by lammyjjones — APPROVED** [review]

**Review by RukayyaBThompson — APPROVED** [review]
Approved

**Review by Marat-Faizov — APPROVED** [review]

**Review by Marat-Faizov — APPROVED** [review]

**Review by Marat-Faizov — APPROVED** [review]

**Comment by wdomanskihmrc** [comment]
@timsb are you able to approve this?

**Review by timsb — APPROVED** [review]

**Comment by wdomanskihmrc** [comment]
@timsb could you possibly merge the branch this once until we get write permissions to more of the team?

**Pull request merged**
